// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consensusMsg.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PreprepareMessage struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PreprepareMessage) Reset()                    { *m = PreprepareMessage{} }
func (m *PreprepareMessage) String() string            { return proto.CompactTextString(m) }
func (*PreprepareMessage) ProtoMessage()               {}
func (*PreprepareMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PreprepareMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PrepareMessage struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *PrepareMessage) Reset()                    { *m = PrepareMessage{} }
func (m *PrepareMessage) String() string            { return proto.CompactTextString(m) }
func (*PrepareMessage) ProtoMessage()               {}
func (*PrepareMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *PrepareMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type CommitMessage struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CommitMessage) Reset()                    { *m = CommitMessage{} }
func (m *CommitMessage) String() string            { return proto.CompactTextString(m) }
func (*CommitMessage) ProtoMessage()               {}
func (*CommitMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CommitMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PreprepareMessage)(nil), "protos.PreprepareMessage")
	proto.RegisterType((*PrepareMessage)(nil), "protos.PrepareMessage")
	proto.RegisterType((*CommitMessage)(nil), "protos.CommitMessage")
}

func init() { proto.RegisterFile("consensusMsg.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 109 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4a, 0xce, 0xcf, 0x2b,
	0x4e, 0xcd, 0x2b, 0x2e, 0x2d, 0xf6, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x03, 0x53, 0xc5, 0x4a, 0xea, 0x5c, 0x82, 0x01, 0x45, 0xa9, 0x05, 0x45, 0xa9, 0x05, 0x89, 0x45,
	0xa9, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x60, 0xb6, 0x92, 0x0a, 0x17, 0x5f, 0x00, 0x61, 0x55,
	0xca, 0x5c, 0xbc, 0xce, 0xf9, 0xb9, 0xb9, 0x99, 0x25, 0x78, 0x14, 0x25, 0x41, 0xec, 0x36, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe6, 0x81, 0xe8, 0x98, 0x00, 0x00, 0x00,
}
