// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Envelope
	Empty
	Message
	Block
	Transaction
	PeerTable
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Envelope struct {
	// marshalled Message
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// signed Message
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// sender's public key
	Pubkey []byte `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Envelope) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Envelope) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Envelope) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Message struct {
	Channel []byte `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// Types that are valid to be assigned to Content:
	//	*Message_Block
	//	*Message_Transaction
	//	*Message_PeerTable
	Content isMessage_Content `protobuf_oneof:"content"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isMessage_Content interface {
	isMessage_Content()
}

type Message_Block struct {
	Block *Block `protobuf:"bytes,2,opt,name=block,oneof"`
}
type Message_Transaction struct {
	Transaction *Transaction `protobuf:"bytes,3,opt,name=transaction,oneof"`
}
type Message_PeerTable struct {
	PeerTable *PeerTable `protobuf:"bytes,4,opt,name=peerTable,oneof"`
}

func (*Message_Block) isMessage_Content()       {}
func (*Message_Transaction) isMessage_Content() {}
func (*Message_PeerTable) isMessage_Content()   {}

func (m *Message) GetContent() isMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetChannel() []byte {
	if m != nil {
		return m.Channel
	}
	return nil
}

func (m *Message) GetBlock() *Block {
	if x, ok := m.GetContent().(*Message_Block); ok {
		return x.Block
	}
	return nil
}

func (m *Message) GetTransaction() *Transaction {
	if x, ok := m.GetContent().(*Message_Transaction); ok {
		return x.Transaction
	}
	return nil
}

func (m *Message) GetPeerTable() *PeerTable {
	if x, ok := m.GetContent().(*Message_PeerTable); ok {
		return x.PeerTable
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Block)(nil),
		(*Message_Transaction)(nil),
		(*Message_PeerTable)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_Block:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Block); err != nil {
			return err
		}
	case *Message_Transaction:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Transaction); err != nil {
			return err
		}
	case *Message_PeerTable:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerTable); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Content has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // content.block
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Block)
		err := b.DecodeMessage(msg)
		m.Content = &Message_Block{msg}
		return true, err
	case 3: // content.transaction
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Transaction)
		err := b.DecodeMessage(msg)
		m.Content = &Message_Transaction{msg}
		return true, err
	case 4: // content.peerTable
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerTable)
		err := b.DecodeMessage(msg)
		m.Content = &Message_PeerTable{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// content
	switch x := m.Content.(type) {
	case *Message_Block:
		s := proto.Size(x.Block)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Transaction:
		s := proto.Size(x.Transaction)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PeerTable:
		s := proto.Size(x.PeerTable)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Block struct {
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Transaction struct {
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type PeerTable struct {
}

func (m *PeerTable) Reset()                    { *m = PeerTable{} }
func (m *PeerTable) String() string            { return proto.CompactTextString(m) }
func (*PeerTable) ProtoMessage()               {}
func (*PeerTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Envelope)(nil), "message.Envelope")
	proto.RegisterType((*Empty)(nil), "message.Empty")
	proto.RegisterType((*Message)(nil), "message.Message")
	proto.RegisterType((*Block)(nil), "message.Block")
	proto.RegisterType((*Transaction)(nil), "message.Transaction")
	proto.RegisterType((*PeerTable)(nil), "message.PeerTable")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Gossip service

type GossipClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (Gossip_StreamClient, error)
	// Ping is used to probe a remote peer's aliveness
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type gossipClient struct {
	cc *grpc.ClientConn
}

func NewGossipClient(cc *grpc.ClientConn) GossipClient {
	return &gossipClient{cc}
}

func (c *gossipClient) Stream(ctx context.Context, opts ...grpc.CallOption) (Gossip_StreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Gossip_serviceDesc.Streams[0], c.cc, "/message.Gossip/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &gossipStreamClient{stream}
	return x, nil
}

type Gossip_StreamClient interface {
	Send(*Envelope) error
	Recv() (*Envelope, error)
	grpc.ClientStream
}

type gossipStreamClient struct {
	grpc.ClientStream
}

func (x *gossipStreamClient) Send(m *Envelope) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gossipStreamClient) Recv() (*Envelope, error) {
	m := new(Envelope)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gossipClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/message.Gossip/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gossip service

type GossipServer interface {
	Stream(Gossip_StreamServer) error
	// Ping is used to probe a remote peer's aliveness
	Ping(context.Context, *Empty) (*Empty, error)
}

func RegisterGossipServer(s *grpc.Server, srv GossipServer) {
	s.RegisterService(&_Gossip_serviceDesc, srv)
}

func _Gossip_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GossipServer).Stream(&gossipStreamServer{stream})
}

type Gossip_StreamServer interface {
	Send(*Envelope) error
	Recv() (*Envelope, error)
	grpc.ServerStream
}

type gossipStreamServer struct {
	grpc.ServerStream
}

func (x *gossipStreamServer) Send(m *Envelope) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gossipStreamServer) Recv() (*Envelope, error) {
	m := new(Envelope)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Gossip_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Gossip/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gossip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Gossip",
	HandlerType: (*GossipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Gossip_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Gossip_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x93, 0xef, 0xb7, 0x4d, 0xcc, 0xc4, 0x0a, 0x0e, 0x22, 0xa1, 0x78, 0x90, 0x3d, 0x48,
	0x4f, 0x45, 0xa2, 0x07, 0xcf, 0x85, 0x62, 0x2f, 0x42, 0x89, 0x3d, 0x79, 0xdb, 0xc4, 0x21, 0x0d,
	0x4d, 0x76, 0x97, 0xec, 0x56, 0xc8, 0xff, 0xe7, 0x1f, 0x26, 0xd9, 0xe6, 0x47, 0xd1, 0xe3, 0x9b,
	0xf7, 0x1e, 0x9f, 0x9d, 0x59, 0x98, 0x55, 0xa4, 0x35, 0xcf, 0x69, 0xa9, 0x6a, 0x69, 0x24, 0xfa,
	0x9d, 0x64, 0x1f, 0x70, 0xb1, 0x16, 0x5f, 0x54, 0x4a, 0x45, 0x18, 0x81, 0xaf, 0x78, 0x53, 0x4a,
	0xfe, 0x19, 0xb9, 0xf7, 0xee, 0xe2, 0x32, 0xe9, 0x25, 0xde, 0x41, 0xa0, 0x8b, 0x5c, 0x70, 0x73,
	0xac, 0x29, 0xfa, 0x67, 0xbd, 0x71, 0x80, 0xb7, 0xe0, 0xa9, 0x63, 0x7a, 0xa0, 0x26, 0xfa, 0x6f,
	0xad, 0x4e, 0x31, 0x1f, 0xa6, 0xeb, 0x4a, 0x99, 0x86, 0x7d, 0xbb, 0xe0, 0xbf, 0x9d, 0x80, 0x2d,
	0x24, 0xdb, 0x73, 0x21, 0xa8, 0xec, 0x21, 0x9d, 0xc4, 0x07, 0x98, 0xa6, 0xa5, 0xcc, 0x0e, 0x16,
	0x10, 0xc6, 0x57, 0xcb, 0xfe, 0xc9, 0xab, 0x76, 0xba, 0x71, 0x92, 0x93, 0x8d, 0x2f, 0x10, 0x9a,
	0x9a, 0x0b, 0xcd, 0x33, 0x53, 0x48, 0x61, 0x99, 0x61, 0x7c, 0x33, 0xa4, 0x77, 0xa3, 0xb7, 0x71,
	0x92, 0xf3, 0x28, 0xc6, 0x10, 0x28, 0xa2, 0x7a, 0xc7, 0xd3, 0x92, 0xa2, 0x89, 0xed, 0xe1, 0xd0,
	0xdb, 0xf6, 0xce, 0xc6, 0x49, 0xc6, 0xd8, 0x2a, 0x00, 0x3f, 0x93, 0xc2, 0x90, 0x30, 0xed, 0x3e,
	0xf6, 0x29, 0x6c, 0x06, 0xe1, 0x19, 0x85, 0x85, 0x10, 0x0c, 0xe5, 0x78, 0x0f, 0xde, 0xab, 0xd4,
	0xba, 0x50, 0xf8, 0x0c, 0xde, 0xbb, 0xa9, 0x89, 0x57, 0x78, 0x3d, 0x40, 0xfa, 0x5b, 0xcf, 0xff,
	0x8e, 0x98, 0xb3, 0x70, 0x1f, 0x5d, 0x5c, 0xc0, 0x64, 0x5b, 0x88, 0x1c, 0xc7, 0xf5, 0xed, 0x0d,
	0xe7, 0xbf, 0x34, 0x73, 0x52, 0xcf, 0x7e, 0xe5, 0xd3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09,
	0x03, 0xcb, 0x17, 0xdb, 0x01, 0x00, 0x00,
}
