#!/bin/bash
diff <(goimports -d $(find . -type f -name '*.go' -not -path "*/vendor/*")) <(printf "")

if [ $? -ne 0 ]; then
  echo "goimports format error" >&2
  exit 1
fi

go test -v ./...

if [ $? -ne 0 ]; then
  echo "go test fail" >&2
  exit 1
fi

go test -v -covermode=count -coverprofile=coverage.out

if [ $? -ne 0 ]; then
  echo "go test coverage fail" >&2
  exit 1
fi

goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

if [ $? -ne 0 ]; then
  echo "go update test coverage fail" >&2
  exit 1
fi

exit 0
